version: '2'
services:
  db:
    image: ealgis/postgis:latest
    volumes:
      - ./:/app

  dataloader:
    image: ealgis/ingest-base:latest
    volumes:
      - ./:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
    - db
